### ISSUE TITLE
[1.14.3] Loading clientside code on dedicated server- Server Crash. Sidedness issue.

### ISSUE THREAD

**Issue by ProsperCraft** [Da-Technomancer/Essentials#13]
Relevant log stacktrace - 
https://gist.github.com/ProsperCraft/cb97406ec85cc4288ca34e319e189321

Crash report-
https://gist.github.com/ProsperCraft/b5632b9ee331a92a0b25eb387e376398

Full debug log-
https://gist.github.com/ProsperCraft/ddfdd0f96cff0f4acfe3685988a20105

Modpack-
https://www.curseforge.com/minecraft/modpacks/ocean-islands-adventure/

**Comment by Da-Technomancer** [comment]
Closed in latest version
