### ISSUE TITLE
Hopper ilter cleared on world load

### ISSUE THREAD

**Issue by ThisIsNotMe1612** [Da-Technomancer/Essentials#14]
Everytime i open up my world in 1.14.3 the filters i set up at my fish farm to trash the fish reset resulting in ALL items being trashed.

Kind of depressing...

**Comment by Da-Technomancer** [comment]
This feature was fixed in Essentials 2.1.3, which can be downloaded from Curse here: https://www.curseforge.com/minecraft/mc-mods/essentials/files/2734374

Just update your Essentials to the latest version.

Sorry this caused so much havoc in the meanwhile, though.
