### ISSUE TITLE
[Bug] Basic item splitter not sending message in chat to player

### ISSUE THREAD

**Issue by VoidSorc** [Da-Technomancer/Essentials#18]
Mc Version: 1.14.4
Mod Loader: Forge 28.0.88
Essentials version: 1.14.4-2.4.1
Config changes: None

**Comment by Da-Technomancer** [comment]
This is actually a forge bug- see https://github.com/MinecraftForge/MinecraftForge/issues/6133 and the pending PR to fix it: https://github.com/MinecraftForge/MinecraftForge/pull/6114
The joys of Forge for MC1.14 being in beta :)
