### ISSUE TITLE
Delete the entire production package

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Essentials#2]
Sooooooo I accidentally didn't put the entire production package/folder in the gitignore file initially, so a large package that isn't supposed to be on github ever is now on github (it should never be put on github as it is large, and is re-generated whenever the mod is compiled, meaning distribution is pointless). I don't actually know how to remove an entire package at once from Github, but if anyone were to make a pull request that did nothing but remove that entire package somehow it would speedily be accepted.

**Comment by LemADEC** [comment]
use `git rm classes` from the git console to remove it, then commit your changes.
