### ISSUE TITLE
[1.14.4] Hoppers cannot extract items from minecarts

### ISSUE THREAD

**Issue by HyCraftHD** [Da-Technomancer/Essentials#20]
The high throughput hopper cannot extract items from a hopper minecart / hopper chest entity. It doesn't matter if its on a rail or not.

The vanilla hopper uses the method ``getInventoryAtPosition`` in HopperTileEntity to search for adjacent inventories. This method also include entity inventories that support minecarts as show here:

``` java
if (iinventory == null) {
         List<Entity> list = worldIn.getEntitiesInAABBexcluding((Entity)null, new AxisAlignedBB(x - 0.5D, y - 0.5D, z - 0.5D, x + 0.5D, y + 0.5D, z + 0.5D), EntityPredicates.HAS_INVENTORY);
         if (!list.isEmpty()) {
            iinventory = (IInventory)list.get(worldIn.rand.nextInt(list.size()));
         }
      }
```

EDIT:
I have made a pull request that implements this logic

**Comment by Da-Technomancer** [comment]
Closes in PR 21

**Comment by HyCraftHD** [comment]
Any chance for a build on curseforge soon?

**Comment by Da-Technomancer** [comment]
Done! https://www.curseforge.com/minecraft/mc-mods/essentials/files/2818382
Thanks for reminding me, I had meant to wait 2 days after the initial PR to merge it with any other bugfixes that popped up, and it completely slipped my mind :)

**Comment by HyCraftHD** [comment]
Thank you very much! Keep up the gook work!
