### ISSUE TITLE
Sorting hoppers not working correctly?

### ISSUE THREAD

**Issue by HYPExMon5ter** [Da-Technomancer/Essentials#29]
**Describe the bug**
The sorting hoppers are not behaving like normal hoppers, now I may be using them wrong or something as I have no found much documentation or any vids or anything explaining it, but doesn't seem to be working right. When you make up a sorting system it seems to only sort the last hopper in the row. If I'm using them wrong, please tell or show me how to use them lol.

**Expected behavior**
The items should be sorted as they flow through the hoppers like normal hoppers do

**Video of the issue**
https://youtu.be/s0tidgtYdic

**Comment by Da-Technomancer** [comment]
You aren't using sorting hoppers correctly. This is a common point of confusion:
Sorting hoppers (and high throughput hoppers) need to be pointed into the sorted output, and the pulling (from either a pipe, or another hopper) is the unsorted hopper. So for your video, have your high-throughput hoppers in a column, with each hopper pointed sideways into the hopper filters. The unsorted items will all be at the bottom. 

There are ways to do it horizontally as well if you want that- but that usually involves item shifters.

**Comment by HYPExMon5ter** [comment]
Mind throwing in a screenshot or video for reference please?

**Comment by Da-Technomancer** [comment]
https://www.curseforge.com/minecraft/mc-mods/essentials/screenshots
Second image on the curseforge shows a simple sorting hopper setup.
In the photo, each slotted chest can only accept certain items. You could replace those with hopper filters going to an item shifter, or any other filtered input. Unsorted items end up in the bottom chest.
