### ISSUE TITLE
Suggestion: Candle lily pads do not melt ice

### ISSUE THREAD

**Issue by UvMidnight** [Da-Technomancer/Essentials#37]
Akin to jack-o-lanterns/pumpkins, candle lily pads should be able to be placed without melting ice. Currently, they melt ice.

Lily pads on ice, whats not to love?

**Comment by Da-Technomancer** [comment]
....jack-o-lanterns _do_ melt ice (or at least, I can't find any mention of this on the wiki, or anything about this in the code).
This would make candle lilypads unique of all light sources- and it's also not clear how this would work.
