### ISSUE TITLE
Patchouli book does not have a texture.

### ISSUE THREAD

**Issue by ChrisJacobsJr** [Da-Technomancer/Essentials#39]
**Describe the bug**
The patchouli guide book has the purple and black checkerboard missing texture. It works fine otherwise.

**To Reproduce [Optional]**
From TMI search bar, type @patchouli and looking for the mod's guidebook,
OR
craft/spawn the patchouli guide book

**Additional context [Optional]**
Have essentials 2.9.1 (latest)
Have Patchouli 1.16-42 (latest)

**Comment by Da-Technomancer** [comment]
This is actually a known bug with Patchouli, not an Essentials bug.
