### ISSUE TITLE
Suggestion*

### ISSUE THREAD

**Issue by DaggerTM** [Da-Technomancer/Essentials#4]
Add a config option to disable to book on login. Couldn't find one there.

**Comment by Da-Technomancer** [comment]
The config option exists, but its part of the GuideAPI config (GuideAPI adds a config for every book added through it). Also, the books that you're referring to (Mysterious Journal and Technician's Manual) are added by Crossroads, not Essentials.

**Comment by DaggerTM** [comment]
oh oops, I thought I put this on the Crossroads issues. Thanks
