### ISSUE TITLE
Wireless redstone not working as expected

### ISSUE THREAD

**Issue by tomte55** [Da-Technomancer/Essentials#42]
When linking 2 transmitters to 1 receiver, only one of the transmitters will transmit the redstone signal to the receiver.
While it clearly shows both transmitters are linked.

**Comment by Da-Technomancer** [comment]
That's a purely visual issue. Only one transmitter is supposed to be able to transmit to a receiver- 1 transmitter can have multiple receivers, but one receiver can only have one transmitter.

The bug is that both transmitters looks linked to the receivers, when the other should visually unlink.

**Comment by tomte55** [comment]
Ok thank you. I later looked at the code and drew that conclusion aswell but i was not completely sure
