### ISSUE TITLE
The width of tooltip should be limited

### ISSUE THREAD

**Issue by kappa-maintainer** [Da-Technomancer/Essentials#44]
**Suggestion**
The width of tooltips should be limited to lesser than half of the window length so players can read it fully.

**Current Behavior [Optional]**
One item's tooltip is out of the window in 1920\*1080, and most of items' tooltips are out of window in 854\*480
![2020-11-06_18 55 36](https://user-images.githubusercontent.com/11038263/98359184-c17cd680-2062-11eb-8446-2b2928e9a529.png)

**Justification**
Some tooltips are unreadable, and this should not happen.

**Comment by Da-Technomancer** [comment]
The portion of the user's screen that a tooltip takes up depends on their screen resolution and their UI size setting. What overflows for one person might not for another.
I can't control people's screen resolutions. There are lots of vanilla tooltips that overflow on high UI size settings for certain resolution screens. In extreme cases, there are vanilla _item names_ that overflow. 

I suggest you either turn down your UI size temporarily to read the tooltips that overflow, or get the information from the ingame guidebook (all the information in the tooltips is also in the book).
