### ISSUE TITLE
ComputerCraft circuit support

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Essentials#47]
**Scope**
One new block, with ComputerCraft interaction. Game balance not affected. 

**Suggestion**
A peripheral block (or some way of directly connecting?) that allows ComputerCraft computers to read/create Essentials circuit signals with the full range of values. As the original ComputerCraft isn't on 1.16.4, this suggestion would mainly apply to the (spiritual successor) [CC Tweaked](https://github.com/SquidDev-CC/CC-Tweaked) instead. 

**Justification**
ComputerCraft integration would enable a lot of cross-mod interaction with Essentials circuits, as CC computers can act as an intermediary. 

**Impact**
Low impact; no impact without ComputerCraft installed. Makes the circuit system more applicable with other mods.

**Comment by The-Minecraft-Scientist** [comment]
👍

**Comment by Random-Scientist** [comment]
Possibly in the form of a circuit plate similar to the redstone splice plate and accessible from the wrench menu? (honestly this feature would still be useful if it was just CC and Essentials)
