### ISSUE TITLE
Unstackables Stack to 16 in Slotted Chests

### ISSUE THREAD

**Issue by Random-Scientist** [Da-Technomancer/Essentials#48]
Suggestion:
Allow unstackable exact duplicates to stack to 16 in slotted chests
Current behavior:
Unstackables will reserve a slot, but will only stack to 1
Reasoning:
This would facilitate simple and compact unstackable sorting setups as well as provide a great way to store duplicate unstackables, like enchanted books or tools.

**Comment by Da-Technomancer** [comment]
It's already possible to sort unstackables using hopper filters, and slotted chests aren't meant for bulk storage like that.
