### ISSUE TITLE
Quark item pipes cause item splitter to only use one side

### ISSUE THREAD

**Issue by SevereOverfl0w** [Da-Technomancer/Essentials#55]
**Describe the bug**
Inserting into the item splitter using Quark oddities item pipes causes the item splitter to only insert into the output that has the gold rimm.

**To Reproduce [Optional]**
Screenshot is the simplest case.

**Expected behavior [Optional]**

As when a hopper is on top, items are split evenly between the two outputs.

**Screenshots [Optional]**
![2021-03-21_15 59 54](https://user-images.githubusercontent.com/6136282/111911722-9964a180-8a5e-11eb-9c84-9fb4c9015884.png)

**Comment by SevereOverfl0w** [comment]
Tried switching over to transport pipes & item shifter, and am seeing the same thing!  So Quark can be ruled out.

Works fine with a hopper connected directly though.

**Comment by Da-Technomancer** [comment]
Which Essentials version are you using?

**Comment by SevereOverfl0w** [comment]
1.16.5-2.10.2 with forge 36.1.1

**Comment by SevereOverfl0w** [comment]
![2021-03-22_21 05 43](https://user-images.githubusercontent.com/6136282/112058388-73b8c480-8b52-11eb-935e-fb9b5feb6397.png)

Repro for essentials only (no other mods in pack).  Place items into the hopper, directly into the shifter works fine.
