### ISSUE TITLE
Auto crafting table crafts only 1 item at a time

### ISSUE THREAD

**Issue by thierryjacoel** [Da-Technomancer/Essentials#56]
**Suggestion**
The auto crafting table should be able to craft a whole stack of items if the resources are sufficient.

**Current Behavior [Optional]**
When the auto crafting table has a stack of material, the recipe is produced for a single item on each redstone tick.

**Justification**
That would allow better automation, especially when auto crafting large amount of material, such as log > planks > sticks

**Comment by Da-Technomancer** [comment]
This is a request for a balance change. 
The answer is no.
