### ISSUE TITLE
Sorting hoppers don't always work correctly.

### ISSUE THREAD

**Issue by Jdewi12** [Da-Technomancer/Essentials#6]
On the mod page is an example of a sorting system created by vertically stacking sorting hoppers facing sideways into chests. This works fine; however, using a similar system but partly horizontally doesn't work, like in this image:
![2018-09-03_16 10 23](https://user-images.githubusercontent.com/25410318/45033357-a0da2000-b097-11e8-9dd0-ec881551e396.png)

You'd expect the chests to be filled in order, but after filling the first one they bypass any other chests and start filling the last one.

**Comment by Da-Technomancer** [comment]
Such a setup isn't intended to work. The sorting hoppers are only guaranteed to sort correctly if they are allowed to withdraw the item they are sorting from the inventory above themselves. If another hopper inserts into them, there is no such guarantee.

**Comment by Jdewi12** [comment]
Ah, I guess that makes sense from a programming perspective, though it's pretty counterintuitive as a player. 

Maybe you could fix this by having the input slot be impossible to withdraw from, and moving the item in the input slot to an output slot after attempting to insert first, kind of like how you can't withdraw from the input of a furnace?

Either way, now that I understand how they work I was finally able to get them working by feeding into a chest and then extracting out of that, rather than feeding directly into the sorting hopper, so I guess it's not a big issue.
