### ISSUE TITLE
Auto-Crafter redstone changes

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Da-Technomancer/Essentials#60]
compatibility for comparator ( ingredients )

1 redstone tick = a recipe

continuous redstone impulse = continuous recipe making

auto imput / export ingredient / resoult from any invetory blocks

**Comment by Da-Technomancer** [comment]
Duplicate of #56

**Comment by AlleCraft-alterego** [comment]
compatibility for comparator ?
