### ISSUE TITLE
Autocrafter and Wireless Transmitter/Receiver link crashes

### ISSUE THREAD

**Issue by LupusVentus** [Da-Technomancer/Essentials#65]
**Description**
The game crashes. (Duh)

**Steps to reproduce:**
    Place and open Autocrafter - results in a crash
    Place Wireless Transmitter and Receiver, try to connect them - results in a crash

**Additional info**
Minecraft 1.17.1
Forge 37.0.103
Mod list is in the logs

Attaching logs: first one is for autocrafter crash, second one is for wireless t/r link
[crash-2021-10-25_12.15.29-client.txt](https://github.com/Crossroads-Development/Essentials/files/7409325/crash-2021-10-25_12.15.29-client.txt)
[crash-2021-10-25_12.17.34-client.txt](https://github.com/Crossroads-Development/Essentials/files/7409328/crash-2021-10-25_12.17.34-client.txt)

**Comment by Da-Technomancer** [comment]
This issue is fixed in the latest update.
https://www.curseforge.com/minecraft/mc-mods/essentials/files/3504275
