### ISSUE TITLE
[1.18.1] Patchouli "use_resource_pack true" causing massive lag on advancements

### ISSUE THREAD

**Issue by itsdinkd** [Da-Technomancer/Essentials#67]
https://github.com/VazkiiMods/Patchouli/issues/481#issuecomment-998190592

As the Occultism dev discovered, having this feature on in the patchouli book causes massive amount of lag when getting a achievement, which also occurred on ATM7.

Please change "use_resource_pack" from true to false and move the book back into /data as what the occultism dev did to fix their part

![image](https://user-images.githubusercontent.com/35115304/147149460-a7fcf3c2-8715-4997-998a-59f79faf284b.png)

**Comment by Da-Technomancer** [comment]
This is an issue with Patchouli which will presumably be fixed on their end at some point.
Using resource packs makes it possible to packmakers and server owners to modify the book using datapacks, which is desirable.

**Comment by itsdinkd** [comment]
I am a pack maker and this has existed since release, and has occurred on ATM7 since patchouli release until Occultism did their part and got rid of `use_resource_pack`.

I promise you massive lag when getting advancements is not desired.
