### ISSUE TITLE
Basic item splitter deletes all items input into it

### ISSUE THREAD

**Issue by EvergreenSystems** [Da-Technomancer/Essentials#68]
**Describe the bug**
All items piped into the basic item splitter are deleted, and do not make it to any outputs.

**Additional context [Optional]**
Mod version 1.18.1-2.13.1
Forge version 39.0.5

The other item splitter (redstone controlled) seems to function as normal, issue is limited to the basic splitter.

**Comment by Da-Technomancer** [comment]
Fixed in commit 34660e3

By the way, in case you lost a valuable item to this bug: It wasn't actually deleted, it just wasn't being output by the splitter and is still stored by the machine. Once you update, the splitter should spit out any items it accepted if you haven't broken it yet.
