### ISSUE TITLE
Filter causing lag [2.13.2]

### ISSUE THREAD

**Issue by itsdinkd** [Da-Technomancer/Essentials#71]
https://spark.lucko.me/rU2tqtI6r5?hl=29 

as shown in the above profiler, the Essentials Filter is causing lag

**Comment by Da-Technomancer** [comment]
Thank you for taking the time to run a profiler on the mod and report it with the output; I often don't have the ability to test performance as thoroughly as I would like, and these types of reports are really helpful.
