### ISSUE TITLE
[suggestion/request] fluid port extender

### ISSUE THREAD

**Issue by majijn** [Da-Technomancer/Essentials#8]
im not sure if it's something youd want to add, but I keep finding I need to be able to pull fluids from the bottom face of a block, but I have  nothing that can pull fluids above them, would it be possible for essentials to add a block of which all faces act as the face of a fluid container  it is connected to?

so like the item port extender, except it acts as ONLY the face it is connected to.

**Comment by Da-Technomancer** [comment]
I have to ask- what's the use case for this? 
What mod/modpack are you playing that doesn't allow pulling fluids from the bottom side?
I've never heard of a mod with a feature like that, so it's possible that the mod you're using is just bugged or confusing.

**Comment by majijn** [comment]
immersive engineering can't pull from a bottom face, only top or sides, with its pumps, and astral sorcery's lightwells can only output from the bottom face
and astral sorcery's containment chalices also can only in/out from the bottom.
pushing into chalices with IE isnt a problem, but pulling is; same with the lightwells.

I've had to add because of this other mods that i dont need otherwise; except that those mods just dont pull fast enough  to keep up with the liquid starlight generation once I start ramping it up

**Comment by Da-Technomancer** [comment]
This feature is a bit too specific for Essentials, sorry.

For your specific case, I'd suggest using something like https://minecraft.curseforge.com/projects/fluid-funnel
which adds only a fluid hopper that would work for what you want.

 The inability of Immersive Engineering pumps to draw from the bottom side is strange- and seems like an oversight. I'd suggest asking the Immersive Engineering dev to add a way to pull fluids from the bottom face.

**Comment by majijn** [comment]
not an oversight, its fully intended. apparently.
im aware of the fluid funnel mod, and in fact I have it, it's just that I dont want to have to buff the funnel for it to be able to keep up...and then just make IE's pump worthless

I had to try to see if you'd be keen on adding it, I understand why you wont, 
thanks for this awesome mod btw! it makes some contraptions so much more intuitive to make!
