### ISSUE TITLE
[1.19.2] Redstone Transmitter crash on server.

### ISSUE THREAD

**Issue by Gbergz** [Da-Technomancer/Essentials#85]
**Describe the bug**
Crash when using the Redstone Transmitter.
(Exception in server tick loop).

**To Reproduce [Optional]**
1. Play around with the Redstone Transmitter 
2. Be on a server.
3. Break it or replace it.
4. Crash

**Expected behavior [Optional]**
That the server doesn't crash when using the Redstone Transmitter.

**Screenshots [Optional]**
No response.

**Additional context [Optional]**
Forge: 43.1.39
Mc: 1.19.2
Essentials: 2.15.2 | https://www.curseforge.com/minecraft/mc-mods/essentials/files/3901142

Crash report: https://gist.github.com/Gbergz/88a0092f94e8ff38ce4b731efd0dd542

**Comment by Da-Technomancer** [comment]
This issue was actually fixed in 683cbbdfaf34b0d8e3bcbdd25a27c3841e96abbe but the update wasn't published.
I've gone ahead and published the fix to Curseforge, it's Essentials 2.15.3: https://www.curseforge.com/minecraft/mc-mods/essentials/files/3901142

**Comment by Gbergz** [comment]
Gotcha, thanks for the publish and fix!
