### ISSUE TITLE
Restructuring creative tab.

### ISSUE THREAD

**Issue by Lucksinia** [Da-Technomancer/Essentials#88]
**Scope**
Order of items in creative tab... which should be not much.

**Suggestion**
So, right now, fertile soil is all over the place. I suggest to restructure them to be on one line and not all over the creative tab.
Also, maybe, add all circuits into creative tab?

**Justification**
To the general ease of use.

**Impact**
people will now find exact fertile soil (and, optionally, circuits) easier.

**Comment by Da-Technomancer** [comment]
This will be added when we update to 1.19.3
