### ISSUE TITLE
[1.19.2] Huge lag spikes while travelling in The End and other dimensions.

### ISSUE THREAD

**Issue by Gbergz** [Da-Technomancer/Essentials#89]
**Describe the bug**
There's huge lag spikes while travelling around in The End and other dimensions.

**To Reproduce [hopefully]**
1. Start flying in any direction
2. Keep flying
3. Lag spike start and world stops generating.
4. Spike lasts around 1 minute maybe 1 and a half.
5. World resumes, no lag spike.
6. Repeats after awhile.
7. Profit.

**Expected behavior**
That the lag spike doesn't happen and I can continue generating land.

**Spark Profiler**
I've included a spark profiler which I ran through the lag spikes, it shows "essentials" taking up 54% of the servers performance, which is not normal.
Link: https://spark.lucko.me/GyR1BG5uhu

**Additional context**
I am in a [modpack](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-6)
This started recently and I've not experienced it before, thought it maybe was caused by an update to the mod, but it hasn't updated in awhile, so I am not sure...

**Comment by Gbergz** [comment]
After some research, it might not be this mod afterall. Apologies.

**Comment by Da-Technomancer** [comment]
I think you were right the first time. I've optimized the offending code; turns out the checks Essentials does for if endermen should be allowed to teleport are quite laggy when you're travelling in a dimension with hundreds of them. It'll be fixed in the next version.
