### ISSUE TITLE
crash when using hopper to insert items to interface from AE2

### ISSUE THREAD

**Issue by dkmk100** [Da-Technomancer/Essentials#92]
**Describe the bug**
The speedy hopper crashes the game when inserting into an interface from AE2
[crash-2023-08-24_15.22.35-server.txt](https://github.com/Crossroads-Development/Essentials/files/12433835/crash-2023-08-24_15.22.35-server.txt)

**To Reproduce [Optional]**
place a speedy hopper from essentials inserting into an interface from AE2
make sure the network is powered/online
game crashes

**Comment by MrDrProfNo** [comment]
Thus far, I've been unable to reproduce the issue. The following setup works just fine:
![image](https://github.com/Crossroads-Development/Essentials/assets/32115458/c07b8638-9ef2-4954-9155-58c651c17c8b)

(the lower hopper is pointing into a flat ME Interface)

Items inserted into either are successfully transported into an ME Drive when one is attached (not pictured above).

This is likely a problem with something in one of the Ars Nouveau related mods.

The error from the above log is:
`java.lang.ClassCastException: class gripe._90.arseng.me.storage.GenericStackSourceStorage cannot be cast to class net.minecraftforge.items.IItemHandler (gripe._90.arseng.me.storage.GenericStackSourceStorage is in module arseng@1.0.0-beta.2 of loader 'TRANSFORMER' @24876a7e; net.minecraftforge.items.IItemHandler is in module forge@43.2.21 of loader 'TRANSFORMER' @24876a7e)`

the mentioned class `gripe._90.arseng.me.storage.GenericStackSourceStorage` is coming out of Ars Energistique - the Essentials hopper asks the ME Interface block if it has an ItemHandler, the Interface says it does, and then returns an object that isn't an Item Handler; that's on them.

However, as mentioned, I'm unable to reproduce the issue; the above screenshot was taken on a game running the following mods:
```
MC 1.19.2, Forge 43.2.21

appliedenergistics2-forge-12.9.7.jar
ars_nouveau-1.19.2-3.17.10.jar
arseng-1.0.0-beta.2.jar
curios-forge-1.19.2-5.1.4.1.jar
essentials-1.19-2.15.5.jar
Patchouli-1.19.2-77.jar
```
Note that this includes Ars Energistique, but there's no error; it may come from one of the other Ars Nouveau related mods that you have installed.

**Comment by dkmk100** [comment]
> Thus far, I've been unable to reproduce the issue. The following setup works just fine: ![image](https://user-images.githubusercontent.com/32115458/263493094-c07b8638-9ef2-4954-9155-58c651c17c8b.png)
> 
> (the lower hopper is pointing into a flat ME Interface)
> 
> Items inserted into either are successfully transported into an ME Drive when one is attached (not pictured above).
> 
> This is likely a problem with something in one of the Ars Nouveau related mods.
> 
> The error from the above log is: `java.lang.ClassCastException: class gripe._90.arseng.me.storage.GenericStackSourceStorage cannot be cast to class net.minecraftforge.items.IItemHandler (gripe._90.arseng.me.storage.GenericStackSourceStorage is in module arseng@1.0.0-beta.2 of loader 'TRANSFORMER' @24876a7e; net.minecraftforge.items.IItemHandler is in module forge@43.2.21 of loader 'TRANSFORMER' @24876a7e)`
> 
> the mentioned class `gripe._90.arseng.me.storage.GenericStackSourceStorage` is coming out of Ars Energistique - the Essentials hopper asks the ME Interface block if it has an ItemHandler, the Interface says it does, and then returns an object that isn't an Item Handler; that's on them.
> 
> However, as mentioned, I'm unable to reproduce the issue; the above screenshot was taken on a game running the following mods:
> 
> ```
> MC 1.19.2, Forge 43.2.21
> 
> appliedenergistics2-forge-12.9.7.jar
> ars_nouveau-1.19.2-3.17.10.jar
> arseng-1.0.0-beta.2.jar
> curios-forge-1.19.2-5.1.4.1.jar
> essentials-1.19-2.15.5.jar
> Patchouli-1.19.2-77.jar
> ```
> 
> Note that this includes Ars Energistique, but there's no error; it may come from one of the other Ars Nouveau related mods that you have installed.

I have also been unable to replicate it so I suspect it was a freak issue with Ars Energistique. I'll look into it on that end.
