### ISSUE TITLE
[NeoForge 1.21] Essentials not recognized as a valid mod file

### ISSUE THREAD

**Issue by FynnWaelsing** [Da-Technomancer/Essentials#99]
Minecraft crashes while loading, giving the error that "File mods\essentials-2.17.0.jar is not a valid mod file." Occurs on a fresh install with only Essentials loaded.

NeoForge Version: 21.0.107-beta
Essentials Version: essentials-2.17.0
latest log: https://pastebin.com/XH17adjk

**Comment by Da-Technomancer** [comment]
Fixed in Essentials 2.17.1.
Sorry about this one- didn't catch that NeoForge really doesn't like non-English letters in the mod credits
